# Configuration for Travis CI
language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - os: osx
      rust: stable
addons:
  apt:
    packages:
      - libssl-dev

# Main build
script:
  # Default features configuration
- cargo build --verbose --all

  # Tests
- cargo test --verbose --all
