# Configuration for Travis CI
language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - libssl-dev
      - xorg-dev

# Main build
script:
  # Default features configuration
- cargo build --verbose --all

  # Other feature combinations 
- cargo build --package ffsend --no-default-features --verbose --all
- cargo build --package ffsend --features no-color --verbose --all

  # Tests
- cargo test --verbose --all
