[package]
name = "ffsend"
version = "0.1.0"
authors = ["timvisee <timvisee@gmail.com>"]

[dependencies]
base64 = "0.9"
chrono = "0.4"
clap = "2.31"
hkdf = "0.3"
hyper = "0.11.9" # same as reqwest
lazy_static = "1.0"
mime_guess = "2.0.0-alpha.2"
open = "1"
openssl = "0.10"
rand = "0.4"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.7"
version-compare = "0.0"
