[package]
name = "ffsend"
version = "0.1.0"
authors = ["timvisee <timvisee@gmail.com>"]

[dependencies]
base64 = "0.9"
clap = "2.30"
hyper = "0.11.9" # same as reqwest
mime_guess = "2.0.0-alpha.2"
open = "1"
rand = "0.4"
reqwest = "0.8"
rust-crypto = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
