[package]
name = "ffsend-api"
version = "0.0.3"
authors = ["Tim Visee <timvisee@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/timvisee/ffsend-api"
repository = "https://github.com/timvisee/ffsend-api"
documentation = "https://docs.rs/ffsend-api"
description = "A fully featured Firefox Send API client."
keywords = ["send", "firefox", "api"]
categories = [
    "api-bindings",
    "authentication",
    "cryptography",
    "network-programming",
]

[badges]
travis-ci = { repository = "timvisee/ffsend-api", branch = "master" }

[lib]
name = "ffsend_api"
path = "src/lib.rs"

[dependencies]
arrayref = "0.3"
base64 = "0.9"
chrono = {version = "0.4", features = ["serde"]}
derive_builder = "0.6"
failure = "0.1"
failure_derive = "0.1"
hkdf = "0.6.1-alpha.0"
hyper = "0.12.7" # same as reqwest
mime = "0.3.10" # same as reqwest
mime_guess = "2.0.0-alpha.4"
openssl = "0.10"
regex = "1.0"
reqwest = "0.9.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.8"
time = "0.1"
url = "1.7"
url_serde = "0.2"

# Patch until an hkdf update is released
[patch.crates-io.hkdf]
git = "https://github.com/timvisee/KDFs.git"
rev = "277cf5d"
